### ISSUE TITLE
dse-server from DataStax as prebuild-requirenment

### ISSUE THREAD

**Issue by 2pk03** [pixie-labs/pixie#272]
Hi community, 

Not sure as what I should classify this, but we try to translate pixie for ARM processors (FreeBSD and Power Architecture) - which works great so far. Unless we hit a dependency which wants to download the dse-server (DataStax Enterprise Server) as a pre-build version. 
Since pixie is on the road to an CNCF project I honestly don't know how to solve this. We didn't found the source within the datastax repo, but the docker images (https://hub.docker.com/r/datastax/dse-server/). Question now: 
- can we somehow replace DSE with a Apache Cassandra stack? 
- would the dependency to an non-open source requirement not break CNCF requirements?
- or can pixie be built without DSE?

Honestly we didn't found a solution - every tip / help is highly appreciated.

thanks and stay safe,
 --Alex

**Comment by oazizi000** [comment]
Hi @2pk03,

The DSE dependency you are seeing is just one for testing purposes (to make sure we are able to trace Cassandra messages). We don't use DSE in the Pixie build itself.

You could just disable that test and its dependency if you just want to build Pixie itself.

Can you also please post more details on the actual error you're seeing?

**Comment by oazizi000** [comment]
Also for reference: #147

**Comment by 2pk03** [comment]
Hi @oazizi000,

thank you - we are working on and comment ASAP. As arm64 is not (yet) supported we donate the outcome, if it works ;)

**Comment by 0x4c4d** [comment]
this is the output:
```
INFO: Repository datastax_base_image instantiated at:
  /home/lukas/Programs/pixie/WORKSPACE:53:17: in <toplevel>
  /home/lukas/Programs/pixie/bazel/pl_workspace.bzl:386:25: in pl_docker_images
  /home/lukas/Programs/pixie/bazel/pl_workspace.bzl:193:33: in _docker_images_setup
  /home/lukas/Programs/pixie/bazel/pl_workspace.bzl:117:19: in stirling_docker_images_setup
Repository rule container_pull defined at:
  /home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/io_bazel_rules_docker/container/pull.bzl:243:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'datastax_base_image':
   Traceback (most recent call last):
	File "/home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
		fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: Timed out (/home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/go_puller_linux_arm64/file/downloaded -directory /home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/datastax_base_image/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/datastax/dse-server@sha256:a98e1a877f9c1601aa6dac958d00e57c3f6eaa4b48d4f7cac3218643a4bfb36e)
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
		fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: Timed out (/home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/go_puller_linux_arm64/file/downloaded -directory /home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/datastax_base_image/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/datastax/dse-server@sha256:a98e1a877f9c1601aa6dac958d00e57c3f6eaa4b48d4f7cac3218643a4bfb36e)
ERROR: /home/lukas/Programs/pixie/src/stirling/source_connectors/socket_tracer/testing/containers/BUILD.bazel:31:16: //src/stirling/source_connectors/socket_tracer/testing/containers:datastax_image depends on @datastax_base_image//image:image in repository @datastax_base_image which failed to fetch. no such package '@datastax_base_image//image': Pull command failed: Timed out (/home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/go_puller_linux_arm64/file/downloaded -directory /home/lukas/.cache/bazel/_bazel_lukas/0aa97e82db3527b1d9c3157330d77fda/external/datastax_base_image/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/datastax/dse-server@sha256:a98e1a877f9c1601aa6dac958d00e57c3f6eaa4b48d4f7cac3218643a4bfb36e)
ERROR: Analysis of target '//src/stirling/source_connectors/socket_tracer/testing/containers:datastax_image' failed; build aborted: Analysis failed
```
